import {
  Utensils,
  Car,
  Gamepad2,
  Receipt,
  ShoppingBag,
  HeartPulse,
  Home,
  PiggyBank,
  Briefcase,
  Laptop,
  TrendingUp,
  Wallet,
  Circle,
  Target,
  Gift,
  Plane,
  Coffee,
  Smartphone,
  Book,
  Music,
  Film,
  Dumbbell,
  GraduationCap,
  Baby,
  Dog,
  Scissors,
  Wrench,
  Zap,
  Droplets,
  Wifi,
  CreditCard,
} from 'lucide-react';

const iconMap = {
  utensils: Utensils,
  car: Car,
  'gamepad-2': Gamepad2,
  receipt: Receipt,
  'shopping-bag': ShoppingBag,
  'heart-pulse': HeartPulse,
  home: Home,
  'piggy-bank': PiggyBank,
  briefcase: Briefcase,
  laptop: Laptop,
  'trending-up': TrendingUp,
  wallet: Wallet,
  circle: Circle,
  target: Target,
  gift: Gift,
  plane: Plane,
  coffee: Coffee,
  smartphone: Smartphone,
  book: Book,
  music: Music,
  film: Film,
  dumbbell: Dumbbell,
  'graduation-cap': GraduationCap,
  baby: Baby,
  dog: Dog,
  scissors: Scissors,
  wrench: Wrench,
  zap: Zap,
  droplets: Droplets,
  wifi: Wifi,
  'credit-card': CreditCard,
};

export const ICON_OPTIONS = Object.keys(iconMap);

export default function CategoryIcon({ name, className, style }) {
  const IconComponent = iconMap[name] || Circle;
  return <IconComponent className={className} style={style} />;
}
